server:
  port: 80

spring:
  application:
    name: manage-back

  thymeleaf:
    prefix:
      classpath: /templates/

  jackson:
    #        date-format: yyyy-MM-dd HH:mm:ss
    #        time-zone: GMT+8
    default-property-inclusion: non-null
    serialization:
      write-dates-as-timestamps: true

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: by123456
    jedis:
      pool:
        max-idle: 20
  datasource:
    name: test
    #      百度数据库
    url: jdbc:mysql://106.13.34.237:3306/sunny?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456

    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  type-aliases-package: com.bin.yang.entity  #解决java jar 运行报错  原先 classpath:**
  mapper-locations: classpath:mapper/**/*.xml

mapper:
  before: true
  not-empty: false


